import type { MacroCatalogEntry } from '../types.js';

export const statusMacros = [
  {
    id: '01JQ7V2H8M4K6C9N3D5F0R1BXP',
    version: '0.1.0',
    group: 'status',
    canonicalName: 'work_started',
    audience: ['shared'],
    severity: 'info',
    priority: 'normal',
    deprecation: { deprecated: false },
    statusKind: 'progress',
  },
  {
    id: '01JQ7W5N2C8M4K9D6F3H0R1BVA',
    version: '0.1.0',
    group: 'status',
    canonicalName: 'work_completed',
    audience: ['shared'],
    severity: 'success',
    priority: 'normal',
    deprecation: { deprecated: false },
    statusKind: 'terminal',
  },
  {
    id: '01JQ7X8C5N2K4M9D6F3H0R1BVT',
    version: '0.1.0',
    group: 'status',
    canonicalName: 'work_blocked',
    audience: ['shared'],
    severity: 'error',
    priority: 'high',
    deprecation: { deprecated: false },
    statusKind: 'terminal',
  },
  {
    id: '01JQ7Y3M8C5N2K9D6F4H0R1BVA',
    version: '0.1.0',
    group: 'status',
    canonicalName: 'decision_required',
    audience: ['operator'],
    severity: 'warning',
    priority: 'high',
    deprecation: { deprecated: false },
    statusKind: 'decision',
  },
  {
    id: '01JQ7Z6N3C8M5K2D9F4H0R1BVA',
    version: '0.1.0',
    group: 'status',
    canonicalName: 'work_failed',
    audience: ['shared'],
    severity: 'error',
    priority: 'high',
    deprecation: { deprecated: false },
    statusKind: 'terminal',
  },
] as const satisfies readonly MacroCatalogEntry[];
